// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('Atlas', []).factory('Atlas', [
    '$route', '$location', function($route, $location) {
      var Atlas;
      Atlas = {
        path: function(name, params) {
          var key, route, routeKey, targetPath, value, _ref;
          targetPath = null;
          _ref = $route.routes;
          for (routeKey in _ref) {
            route = _ref[routeKey];
            if (routeKey) {
              if (route.atlasName === name) {
                targetPath = routeKey;
                break;
              }
            }
          }
          if (targetPath === null) {
            throw "Could not find route named '" + name + "'";
          }
          for (key in params) {
            value = params[key];
            targetPath = targetPath.replace(":" + key, value);
          }
          return targetPath;
        },
        goto: function(name, params) {
          return $location.path(this.path(name, params));
        }
      };
      return Atlas;
    }
  ]);

}).call(this);
